### ISSUE TITLE
how to analyze result

### ISSUE THREAD

**Issue by ktprime** [renzibei/hashtable-bench#2]
**The results of the tests will be in the format of csv files. You can use the jupyter notebook tools/analyze_results.ipynb to parse and generate plots of the results.**

I have finished all tests and generate many csv files, how to use analyze_results.ipynb to generate chart.

**Comment by renzibei** [comment]
Hi, the code in `analyze_results.ipynb` is quite simple. You can read it and learn how the csv is parsed.
Basically, you need to change the variables like `cur_data_dir_name` and `platform_name`.  Make sure all the csv files are under the directory `cur_csv_dir_path`.
